isx-stg:
  script:
    - pushd _isx
    - wget https://releases.hashicorp.com/terraform/1.12.2/terraform_1.12.2_linux_amd64.zip
    - unzip terraform_1.12.2_linux_amd64.zip
    - ./terraform init
    - ./terraform plan -var="ENV=stg" -var "TEST_EMAIL=${TEST_EMAIL}"
    - ./terraform apply -auto-approve -var="ENV=stg" -var "TEST_EMAIL=${TEST_EMAIL}"
