isx-stg:
  image:
    name: hashicorp/terraform:1.12
    entrypoint: [""]
  script:
    - cd _isx/stg
    - terraform init
    - terraform plan -var="TEST_EMAIL=${TEST_EMAIL}"
      -var="AWS_ACCESS_KEY=${AWS_ACCESS_KEY}" -var="AWS_SECRET_KEY=${AWS_SECRET_KEY}"
    - terraform apply -auto-approve -var="ENV=stg" -var "TEST_EMAIL=${TEST_EMAIL}"
      -var="AWS_ACCESS_KEY=${AWS_ACCESS_KEY}" -var="AWS_SECRET_KEY=${AWS_SECRET_KEY}"

isx-prod:
  image:
    name: hashicorp/terraform:1.12
    entrypoint: [""]
  script:
    - cd _isx/prod
    - terraform init
    - terraform plan -var="AWS_ACCESS_KEY=${AWS_ACCESS_KEY}"
      -var="AWS_SECRET_KEY=${AWS_SECRET_KEY}"
    - terraform apply -auto-approve -var="AWS_ACCESS_KEY=${AWS_ACCESS_KEY}"
      -var="AWS_SECRET_KEY=${AWS_SECRET_KEY}"

shell-build:
  image: node:22-alpine
  artifacts:
    paths:
      - shell/dist
  script:
    - cd shell
    - npm ci
    - npm run build

shell-stg:
  image:
    name: amazon/aws-cli:2.27.33
    entrypoint: [""]
  needs:
    - shell-build
    - isx-stg
  dependencies:
    - shell-build
  script:
    - aws s3 sync --delete shell/dist s3://stg-mytasks-shell
