isx-stg:
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  script:
    - terraform init
    - terraform plan -var="ENV=stg" -var="TEST_EMAIL=${TEST_EMAIL}"
      -var="AWS_ACCESS_KEY=${AWS_ACCESS_KEY}" -var="AWS_SECRET_KEY=${AWS_SECRET_KEY}"
    - terraform apply -auto-approve -var="ENV=stg" -var "TEST_EMAIL=${TEST_EMAIL}"
      -var="AWS_ACCESS_KEY=${AWS_ACCESS_KEY}" -var="AWS_SECRET_KEY=${AWS_SECRET_KEY}"

isx-prod:
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  script:
    - terraform init
    - terraform plan -var="ENV=prod" -var="AWS_ACCESS_KEY=${AWS_ACCESS_KEY}"
      -var="AWS_SECRET_KEY=${AWS_SECRET_KEY}"
    - terraform apply -auto-approve -var="ENV=prod" -var="AWS_ACCESS_KEY=${AWS_ACCESS_KEY}"
      -var="AWS_SECRET_KEY=${AWS_SECRET_KEY}"
