name: provision staging infrastructure
run-name: provision staging infrastructure
on:
  push:
    branches: [main]
    paths: [_isx/**]
permissions:
  contents: read
jobs:
  provision:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    environment: staging
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./_isx
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init -input=false
      - run: terraform plan -input=false
      - run: terraform apply -auto-approve -input=false
