name: provision production infrastructure
run-name: provision production infrastructure
on:
  # TODO: should you make it run when all builds complete (i.e. all deploys to staging has started)?
  push:
    branches: [main]
    paths: [_isx/**]
permissions:
  contents: read
jobs:
  provision:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform plan -input=false
      - run: terraform apply -auto-approve -input=false
