name: Build and Deploy Auth Microfrontend
run-name: Build and Deploy Auth Microfrontend
on:
  workflow_run:
    workflows: [Provision Infrastructure]
    branches: [main]
    types: [completed]
permissions:
  contents: read
defaults:
  run:
    working-directory: auth/microfrontend
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
          cache-dependency-path: auth/microfrontend/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit and Integration Tests
        run: npm run test

      - name: Build
        run: npm run build

  deploy-stg:
    name: Deploy to Staging Environment
    needs: build
    runs-on: ubuntu-latest
    permissions:
      actions: read
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Get Infrastructure Workflow Run Reference
        uses: beacon-biosignals/get-workflow-run@v1
        id: infrastructure-workflow-run
        with:
          workflow-file: infrastructure.yml
          commit-sha: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Wait for Staging Infrastructure Provisioning
        uses: beacon-biosignals/wait-for-job@v1
        id: wait-for-infrastructure
        with:
          run-id: ${{ steps.infrastructure-workflow-run.outputs.run-id }}
          job-name: stg

      - name: Deploy
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: dist
          bucket: stg-mytasks-auth
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_STAGING }}
          invalidation: / *

  deploy-prod:
    name: Deploy to Production Environment
    needs: build
    runs-on: ubuntu-latest
    permissions:
      actions: read
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Get End-to-End Tests Workflow Run Reference
        uses: beacon-biosignals/get-workflow-run@v1
        id: e2e-workflow-run
        with:
          workflow-file: e2e.yml
          commit-sha: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Wait for End-to-End Tests to Run
        uses: beacon-biosignals/wait-for-job@v1
        id: wait-for-e2e
        with:
          run-id: ${{ steps.e2e-workflow-run.outputs.run-id }}
          job-name: run

      - name: Get Infrastructure Workflow Run Reference
        uses: beacon-biosignals/get-workflow-run@v1
        id: infrastructure-workflow-run
        with:
          workflow-file: infrastructure.yml
          commit-sha: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Wait for Production Infrastructure Provisioning
        uses: beacon-biosignals/wait-for-job@v1
        id: wait-for-infrastructure
        with:
          run-id: ${{ steps.infrastructure-workflow-run.outputs.run-id }}
          job-name: prod

      - name: Deploy
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: dist
          bucket: prod-mytasks-auth
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_PRODUCTION }}
          invalidation: / *
