name: Run End-to-End Tests
run-name: Run End-to-End Tests
on:
  push:
    branches: [main]
    paths: [shell/**, auth/**, tasks/**, e2e/**]
permissions:
  contents: read
defaults:
  run:
    working-directory: e2e
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Get Frontend Shell Run Reference
        uses: beacon-biosignals/get-workflow-run@v1
        id: shell-workflow-run
        with:
          workflow-file: shell.yml
          # TODO: check if below works - pasted from example: commit-sha: ${{ github.event.pull_request.head.sha }}
          commit-sha: ${{ github.event.push.head.sha }}

      - name: Wait for Frontend Shell Deployment to Staging Environment
        uses: beacon-biosignals/wait-for-job@v1
        id: wait-for-infrastructure
        with:
          run-id: ${{ steps.shell-workflow-run.outputs.run-id }}
          job-name: deploy-stg

      - name: Get Auth Microservice Run Reference
        uses: beacon-biosignals/get-workflow-run@v1
        id: auth-microservice-workflow-run
        with:
          workflow-file: auth-microservice.yml
          # TODO: check if below works - pasted from example: commit-sha: ${{ github.event.pull_request.head.sha }}
          commit-sha: ${{ github.event.push.head.sha }}

      - name: Wait for Auth Microservice Deployment to Staging Environment
        uses: beacon-biosignals/wait-for-job@v1
        id: wait-for-auth-microservice
        with:
          run-id: ${{ steps.auth-microservice-workflow-run.outputs.run-id }}
          job-name: deploy-stg

      - name: Get Auth Microfrontend Run Reference
        uses: beacon-biosignals/get-workflow-run@v1
        id: auth-microfrontend-workflow-run
        with:
          workflow-file: auth-microfrontend.yml
          # TODO: check if below works - pasted from example: commit-sha: ${{ github.event.pull_request.head.sha }}
          commit-sha: ${{ github.event.push.head.sha }}

      - name: Wait for Auth Microfrontend Deployment to Staging Environment
        uses: beacon-biosignals/wait-for-job@v1
        id: wait-for-auth-microfrontend
        with:
          run-id: ${{ steps.auth-microfrontend-workflow-run.outputs.run-id }}
          job-name: deploy-stg

      - name: Get Tasks Microservice Run Reference
        uses: beacon-biosignals/get-workflow-run@v1
        id: tasks-microservice-workflow-run
        with:
          workflow-file: tasks-microservice.yml
          # TODO: check if below works - pasted from example: commit-sha: ${{ github.event.pull_request.head.sha }}
          commit-sha: ${{ github.event.push.head.sha }}

      - name: Wait for Tasks Microservice Deployment to Staging Environment
        uses: beacon-biosignals/wait-for-job@v1
        id: wait-for-tasks-microservice
        with:
          run-id: ${{ steps.tass-microservice-workflow-run.outputs.run-id }}
          job-name: deploy-stg

      - name: Get Tasks Microfrontend Run Reference
        uses: beacon-biosignals/get-workflow-run@v1
        id: tasks-microfrontend-workflow-run
        with:
          workflow-file: tasks-microfrontend.yml
          # TODO: check if below works - pasted from example: commit-sha: ${{ github.event.pull_request.head.sha }}
          commit-sha: ${{ github.event.push.head.sha }}

      - name: Wait for Tasks Microfrontend Deployment to Staging Environment
        uses: beacon-biosignals/wait-for-job@v1
        id: wait-for-tasks-microfrontend
        with:
          run-id: ${{ steps.tasks-microfrontend-workflow-run.outputs.run-id }}
          job-name: deploy-stg

      - name: Run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
