name: Provision Infrastructure
run-name: Provision Infrastructure
on:
  push:
    branches: [main]
    paths: [_isx/**]
  workflow_dispatch:
permissions:
  contents: read
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
jobs:
  stg:
    name: Provision Staging Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: _isx/stg
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - run: ls

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform Files
        run: terraform init -input=false

      - name: Plan Infrastructure
        run: terraform plan -input=false

      - name: Provision Infrastructure
        run: terraform apply -auto-approve -input=false \
          -var="ENV=stg" -var "TEST_EMAIL=${{ secrets.TEST_EMAIL }}"

  prod:
    name: Provision Production Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: _isx/prod
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform Files
        run: terraform init -input=false

      - name: Plan Infrastructure
        run: terraform plan -input=false

      - name: Provision Infrastructure
        run: terraform apply -auto-approve -input=false -var="ENV=prod"
